server:
  port: 8990


spring:
  datasource:
    dynamic:
      primary: db1 #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        db1:
          url: jdbc:mysql://124.221.161.162/trainingsystem?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: gyj
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        db2:
          url: jdbc:mysql://localhost:3306/atguigudb?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: huangjiayu
          driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  redis:
    host: 124.221.161.162
    port: 6379
    database: 0
    connect-timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: huang2001315.



mybatis-plus:
  mapper-locations: com/trainingsystem/trainingSystem/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

